name: dotnet-based-slight-application-on-aks-wasi-node-pool
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
env:
  LOCATION: eastus
  RESOURCE_GROUP: rg-dotnet-on-wasi-node-pool
  CONTAINER_REGISTRY: crdotnetwasi
  AKS_CLUSTER: aks-dotnet-on-wasi-node-pool
  WASI_NODE_POOL: wasinodepool
jobs:
  create-aks-cluster-with-wasi-node-pool:
    runs-on: ubuntu-latest
    steps:
    - name: Install the aks-preview Extension
      run: az extension add --name aks-preview --upgrade
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Create Resource Group
      run: az group create -l ${LOCATION} -g ${RESOURCE_GROUP}
    - name: Create Container Registry
      run: az acr create -n ${CONTAINER_REGISTRY} -l ${LOCATION} -g ${RESOURCE_GROUP} --sku Basic
    - name: Create AKS Cluster
      run: az aks create -n ${AKS_CLUSTER} -l ${LOCATION} -g ${RESOURCE_GROUP} -c 1 --generate-ssh-keys --attach-acr ${CONTAINER_REGISTRY}
    - name: Add a WASM/WASI Node Pool
      run: az aks nodepool add -n ${WASI_NODE_POOL} -g ${RESOURCE_GROUP} -c 1 --cluster-name ${AKS_CLUSTER} --workload-runtime wasmwasi
    - name: Log Out From Azure
      run: |
        az logout
        az cache purge
        az account clear
  build-and-push-slight-application-image:
    needs: [create-aks-cluster-with-wasi-node-pool]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Log in to Container Registry
      run: |
        az acr login -n ${CONTAINER_REGISTRY}
    - name: Build Image
      run: |
        docker build src/Demo.Wasm.Slight/ -t ${CONTAINER_REGISTRY}.azurecr.io/slight-with-dotnet-8:${{ github.sha }}
    - name: Push Image to Container Registry
      run: |
        docker push ${CONTAINER_REGISTRY}.azurecr.io/slight-with-dotnet-8:${{ github.sha }}
    - name: Tag Image as Latest
      run: |
        az acr import --name ${CONTAINER_REGISTRY} --source ${CONTAINER_REGISTRY}.azurecr.io/slight-with-dotnet-8:${{ github.sha }} --image slight-with-dotnet-8:latest
    - name: Log Out From Azure
      run: |
        docker logout
        az logout
        az cache purge
        az account clear
  deploy-slight-application-to-wasm-wasi-node-pool:
    needs: [create-aks-cluster-with-wasi-node-pool, build-and-push-slight-application-image]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Get AKS Credentials
      run: |
        az aks get-credentials -n ${AKS_CLUSTER} -g ${RESOURCE_GROUP}
    - name: Apply AKS Configuration
      run: |
        kubectl apply -f deployments/wasmtime-slight-v1-all-in-one.yaml
    - name: Log Out From Azure
      run: |
        docker logout
        az logout
        az cache purge
        az account clear